author: vemacs
main: me.vemacs.executeeverywhere.ExecuteEverywhere
name: ExecuteEverywhere
version: '1.1'
commands:
  ee:
    description: Dispatches a command for execution.
    aliases: [executeeverywhere]
    permission: executeeverywhere.use
    usage: /ee <cmd>
    permission-message: You don't have permission to use this.
permissions:
  executeeverywhere.use:
    description: Lets you dispatch a command for execution on all servers.
    default: op
